Fast slow query trace
sitano/scylla pull request #1
Opened 2021-03-09 14:59 UTC by sitano

2021-03-09 15:17 UTC, sitano commented on api/storage_service.cc
> +                if (fast != "" || (prev_enabled && (!local_tracing.slow_query_tracing_enabled()))) {
@vladzcloudius you asked > Why all this complexity? Simply set it to True or False similarly what we do to "enable" above. You resolve all the dependency on the on the global Slow Logging enablement in the tracing::fast_slow_query_tracing_enabled()

This is written in this way because I wanted to bring an opportunity to have this fast tracing mode independent - a user can request disabling all tracing events but not sessions and do the trace requests. The second thing `(prev_enabled && (!local_tracing.slow_query_tracing_enabled()))` disables this mode in anyway IF slow query log was enabled and a user forgot to state `,"fast":false` explicitly.

2021-03-09 16:13 UTC, vladzcloudius commented on api/storage_service.cc
> +                if (fast != "" || (prev_enabled && (!local_tracing.slow_query_tracing_enabled()))) {
But it would be disabled even if he/she forgot to set it because of the `&&` in the `tracing::fast_slow_query_tracing_enabled()`.

Let's keep things simple.

2021-03-09 18:51 UTC, vladzcloudius requested changes

2021-03-09 18:51 UTC, vladzcloudius commented on api/storage_service.cc
> +                    local_tracing.set_ignore_trace_events(strcasecmp(fast.c_str(), "true") == 0);
This patch needs to be after the patch that adds `local_tracing.set_ignore_trace_events()`.
Otherwise it's going to break `git bisect`.

2021-03-09 18:51 UTC, vladzcloudius commented on tracing/tracing.hh
> +    void set_ignore_trace_events(bool enable = true) {
All this should be in a separate patch that adds the Slow Query Logging Light functionality to the query processing code.

The order of patches should be as follows:
1) Patch that adds all the bits that would make the new tracing work if it was enabled but doesn't add the bits in the `api/storage_service.cc` yet.
2) Patch that allows enabling the new mode.
3) Unit tests.

2021-03-09 19:06 UTC, vladzcloudius requested changes

2021-03-09 19:06 UTC, vladzcloudius commented on tracing/trace_state.hh
> +        if (!tracing::get_local_tracing_instance().ignore_trace_events_enabled()) {
Please, put this branch to be the second after checking the `state != nullptr` like you did in `tracing::trace(....)` above.

2021-03-09 19:15 UTC, vladzcloudius reviewed
I don't understand why this patch is needed at this stage.
This is in addition to me not understanding what is this `id` thing? Is it a new filtering concept? If yes this should be a separate patch not related to this series.

I thing this patch is a preliminary optimization which requires performance testing justification.

Please, try to follow my recommendations as to order of things:
1) Check the performance overhead of the Slow Query Logging Light as is.
And only if they are not satisfactory (which I have a reason to believe will NOT be the case) we'll try to optimize it further.

2021-03-09 19:21 UTC, vladzcloudius requested changes

2021-03-09 19:21 UTC, vladzcloudius commented on test/boost/tracing.cc
> +        BOOST_CHECK_EQUAL(trace_state->records_size(), 1);
What if it's because there is a single `event` entry and `session_rec.ready() == false`?
You need to check the `trace_state_ptr->_records->events_recs.size()` and it should be `0`.

2021-03-09 19:22 UTC, vladzcloudius reviewed
While `boost` test is fine we need a full-system `dtest`.

2021-03-11 17:22 UTC, sitano commented on api/storage_service.cc
> +                if (fast != "" || (prev_enabled && (!local_tracing.slow_query_tracing_enabled()))) {
done

2021-03-11 17:22 UTC, sitano commented on api/storage_service.cc
> +                    local_tracing.set_ignore_trace_events(strcasecmp(fast.c_str(), "true") == 0);
done

2021-03-11 17:22 UTC, sitano commented on tracing/tracing.hh
> +    void set_ignore_trace_events(bool enable = true) {
fixed

2021-03-11 17:22 UTC, sitano commented on tracing/trace_state.hh
> +        if (!tracing::get_local_tracing_instance().ignore_trace_events_enabled()) {
done

2021-03-11 17:22 UTC, sitano commented on test/boost/tracing.cc
> +        BOOST_CHECK_EQUAL(trace_state->records_size(), 1);
done

2021-03-11 17:25 UTC, sitano commented
> I don't understand why this patch is needed at this stage. (begin() static strings optimization)

I thought I just can do that as well. I dequeued it.

> This is in addition to me not understanding what is this id thing? Is it a new filtering concept? If yes this should be a separate patch not related to this series.

It's a new session parameter property of type string to hold the query id - the only 1 use case of begin(lazy_eval) in the code.

> I thing this patch is a preliminary optimization which requires performance testing justification.

Ok. We can push it later if we want.

> While boost test is fine we need a full-system dtest.

Where should I look at? Have no idea what is dtest.

2021-03-12 13:30 UTC, vladzcloudius requested changes
A few nitpicks however which you'd rather address before posting this on the main repo.

2021-03-12 13:30 UTC, vladzcloudius commented on tracing/trace_state.hh
> +    // still active and only if the sessions events tracing is not explicitly disabled.
"session's events"

2021-03-12 13:30 UTC, vladzcloudius commented on tracing/trace_state.hh
> +                              state->slow_query_threshold_us(), state->slow_query_ttl_sec(), state->my_span_id()};
Please, make sure not to include irrelevant cosmetic changes, like breaking a long line or changing the indentation (which even looks wrong), in the patch that adds a new functionality. 

It makes it much harder to review. 
If really needed add cosmetic changes as the last patch in the series with the corresponding comment.

2021-03-12 13:34 UTC, vladzcloudius requested changes

2021-03-12 13:34 UTC, vladzcloudius commented on tracing/tracing.hh
> +    bool fast_slow_query_tracing_enabled() const {
Where do you use this? If it's not used - kill it.

2021-03-12 13:38 UTC, vladzcloudius requested changes

2021-03-12 13:38 UTC, vladzcloudius commented on tracing/trace_state.hh
> +    if (p && !tracing::get_local_tracing_instance().ignore_trace_events_enabled()) {
What if events logging is disabled by this new API (Slow Query Logging Light is enabled) but then somebody also want to trace a specific query, e.g. using cqlsh + TRACING ON?

In this case the full tracing for that query is expected.

2021-03-12 13:45 UTC, vladzcloudius requested changes
While I find the idea of having "lightweight" mode for any kind of tracing interesting what bothers me here is that the API as it is today allows one to forget that he set the "fast" mode for Slow Query and forgot to disable it for a probabilistic tracing for instance.

Note that all 3 existing Tracing modes can operate at the same time today independently. And I think this is a good thing.

If we want to add the "fast" mode to other Tracing flavors too - we should add them as separate options so that you can toggle it for each of them independently.

I think it would be safer to limit the scope of this series to Slow Query Logging only and put a comment explaining that it may be interesting to consider extending to other Tracing modes too in the future.

2021-03-12 13:49 UTC, vladzcloudius requested changes

2021-03-12 13:49 UTC, vladzcloudius commented on tracing/trace_state.hh
> +        return _records->size();
AFAICT _records->size() is going to return `events_recs.size() + session_rec.ready()`.
What you are interested in however is `events_recs.size()`.
I think I made this comment in the previous round.

2021-03-12 13:51 UTC, vladzcloudius commented on test/boost/tracing.cc
> +        BOOST_CHECK_EQUAL(trace_state->records_size(), 1);
not done. Your `trace_state->records_size()` implementation is still wrong ;)

2021-03-13 13:18 UTC, sitano commented on tracing/trace_state.hh
> +        return _records->size();
> AFAICT _records->size() is going to return events_recs.size() + session_rec.ready().

yes

> What you are interested in however is events_recs.size().

at the test we are fine with both cuz session_rec == 0. from perspective of the API the func has correct name and meaning. 

>I think I made this comment in the previous round.

Nope

2021-03-13 13:19 UTC, sitano commented on tracing/trace_state.hh
> +    if (p && !tracing::get_local_tracing_instance().ignore_trace_events_enabled()) {
I will move state to the trace_state then

2021-03-15 12:53 UTC, sitano commented on tracing/trace_state.hh
> +        return _records->size();
If you specifically want to have trace_state.records_size() to return exactly events_recs.size() then we need to change a `_records->size()` to return `events_recs.size()` because then the impl of `_records->size()` is incorrect regarding the name.

2021-03-15 12:54 UTC, sitano commented on tracing/trace_state.hh
> +    if (p && !tracing::get_local_tracing_instance().ignore_trace_events_enabled()) {
fixed

2021-03-15 12:54 UTC, sitano commented on tracing/tracing.hh
> +    bool fast_slow_query_tracing_enabled() const {
removed

2021-03-15 12:54 UTC, sitano commented on tracing/trace_state.hh
> +    if (p && !tracing::get_local_tracing_instance().ignore_trace_events_enabled()) {
trace_state now has ignore_events flag

2021-03-15 12:54 UTC, sitano commented on tracing/trace_state.hh
> +                              state->slow_query_threshold_us(), state->slow_query_ttl_sec(), state->my_span_id()};
done

2021-03-15 12:54 UTC, sitano commented on tracing/trace_state.hh
> +    // still active and only if the sessions events tracing is not explicitly disabled.
done

2021-03-17 14:08 UTC, sitano commented
> I think it would be safer to limit the scope of this series to Slow Query Logging only and put a comment explaining that it may be interesting to consider extending to other Tracing modes too in the future.

Current implementation ignore tracing events only if the tracing request does not have a flag "full_tracing" and "igore_tracing_events" is true.

2021-03-17 14:21 UTC, vladzcloudius requested changes

2021-03-17 14:21 UTC, vladzcloudius commented on tracing/trace_state.hh
> +    bool _skip_events = false;
Please, add another bit in the `trace_state_props_set` instead.

2021-03-17 14:26 UTC, vladzcloudius requested changes

2021-03-17 14:26 UTC, vladzcloudius commented on tracing/trace_state.hh
> +        _skip_events = !full_tracing() && _local_tracing_ptr->ignore_trace_events_enabled();
This logic should be implemented at the same place where other `trace_state_props_set` are set - namely at the call site of `tracing::create_session(...)`

2021-03-17 15:55 UTC, sitano commented on tracing/trace_state.hh
> +        _skip_events = !full_tracing() && _local_tracing_ptr->ignore_trace_events_enabled();
moved

2021-03-17 15:55 UTC, sitano commented on tracing/trace_state.hh
> +    bool _skip_events = false;
moved

2021-03-17 18:58 UTC, vladzcloudius requested changes
The scylla part of the code looks good except for a cosmetics comment. The test is still broken.

Once you fix that you can send this PR to the scylla repo.

2021-03-17 18:58 UTC, vladzcloudius commented on tracing/tracing.cc
> +        // Ignore events if they are disabled
Please, unbreak this line. Make it a one long line, please.

2021-03-17 18:58 UTC, vladzcloudius commented on transport/server.cc
> +    if (init_trace && trace_state) {
Drop this - this is an optimization. Add this to the next series.

2021-03-17 18:58 UTC, vladzcloudius commented on transport/server.cc
> +    if (init_trace && trace_state) {
Same here - drop here and send it with the rest of optimizations.

2021-03-17 18:58 UTC, vladzcloudius commented on tracing/trace_state.hh
> +        return _records->size();
The implementation of `_records->size()` is correct. It's meant to return the total number of records that would be written by this object in all (!!) tables in total.

What you need here is a different method that you want to add and which would return only the amount of `event` entries.

2021-03-18 08:52 UTC, sitano commented on tracing/trace_state.hh
> +        return _records->size();
got it

2021-03-18 10:37 UTC, sitano commented on tracing/tracing.cc
> +        // Ignore events if they are disabled
done

2021-03-18 10:37 UTC, sitano commented on transport/server.cc
> +    if (init_trace && trace_state) {
done

2021-03-18 10:37 UTC, sitano commented on transport/server.cc
> +    if (init_trace && trace_state) {
done

2021-03-18 16:17 UTC, closed without merging

2021-03-18 16:39 UTC, sitano commented
just a note: moved to the fast_slow_query_trace_public branch / PR