tracing: optimize hot path
sitano/scylla pull request #2
Opened 2021-03-19 15:29 UTC by sitano

2021-03-30 22:12 UTC, vladzcloudius requested changes

2021-03-30 22:12 UTC, vladzcloudius commented on transport/server.cc
> +    if (init_trace && trace_state) {
I don't like this patch: we already have `if (trace_state_ptr)` branch inside of every public `tracing::xx()` function.

I don't see how this patch can deliver any significant improvement when Slow Query Fast is enabled. 
I do see how it can make things worse however.

Note that this patch optimized the "tracing disabled" case on account of "tracing enabled" case.

So, it's counterproductive given the goal of this series.

2021-03-30 22:34 UTC, vladzcloudius requested changes

2021-03-30 22:34 UTC, vladzcloudius commented on tracing/trace_string.cc
> +const char *trace_string_data[] = {
use `std::small_vector<sstring>` instead of C-arrays.

2021-03-30 22:34 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    inline bool is_set(trace_string_enum val) {
Why is this needed?

2021-03-30 22:34 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    inline const char *to_string(trace_string_enum val) {
Implement an `operator*(enum class trace_string_enum)` instead.

The you can get the string value by calling `*enum_val` which is nicer.

2021-03-31 10:29 UTC, sitano commented on transport/server.cc
> +    if (init_trace && trace_state) {
@vladzcloudius you are right that we have `if (trace_state_ptr)` inside. I just thought that we don't want to do multiple branch checking when we can omit doing that. you are also correct that it does not correspond to the purpose of this PR - its just a hot path optimization. I also don't understand why we have those `trace_state` setter private? we could have that public.

do you want me to remove this patch?

2021-03-31 10:43 UTC, sitano commented on tracing/trace_string.hh
> +    inline bool is_set(trace_string_enum val) {
originally I wanted to have a boolean operator overload on the enum class. but turned out to be it's impossible to have functions inside of the enum class. there are workarounds but I did not want it. the default initialization of the enum class is zero-initialization however zero value does not mean it's a default value for an enum class. so I wanted to have a method that explicitly says what is the default value for the type.

it is used in this context
```
if (request.empty() && ::tracing::trace_string::is_set(record.request_type)) {
        request = std::string_view(::tracing::trace_string::to_string(record.request_type));
}
```

otherwise I will have to rewrite it into `&& static_cast<int>(record.request_type)`.

2021-03-31 10:44 UTC, sitano commented on tracing/trace_string.hh
> +    inline const char *to_string(trace_string_enum val) {
ok, but I don't see any advantage from having this logic encapsulated into an operator*. using to_string function is more explicit variant for a reader.

2021-03-31 12:09 UTC, sitano commented on tracing/trace_string.cc
> +const char *trace_string_data[] = {
ok, but this would require adding 2 includes <vector> and "sstring" for nothing.

2021-03-31 12:14 UTC, sitano commented on tracing/trace_string.cc
> +const char *trace_string_data[] = {
reworked

2021-03-31 12:16 UTC, sitano commented
I have done manual testing in Debug and Release mode with tracing trace enabled for slow, fast/slow, probablistic, tracing on, tracing off modes. It works. Fixed 1 bug with missing username and table name.

@vladzcloudius I have added this since 31 march 2021:

```
void trace_state::set_session_records_params() noexcept {
    _records->session_rec.client = _client;
    _records->session_rec.request = _request;
    _records->session_rec.request_type = _request_type;
    _records->session_rec.started_at = _started_at;
    _records->session_rec.request_size = _request_size;
    _records->session_rec.response_size = _response_size;

    if (_params_ptr) {
        _records->session_rec.username = std::move(_params_ptr->username);

        for (const auto &table: _params_ptr->tables) {
            _records->session_rec.tables.emplace(table);
        }
    }
}
```

2021-03-31 12:43 UTC, vladzcloudius requested changes

2021-03-31 12:43 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +    std::string_view request = record.request;
Why is this needed? The whole point is to get rid of records.request and the corresponding copy, no?

2021-03-31 12:43 UTC, vladzcloudius commented on tracing/tracing.hh
> +    trace_string_enum request_type = {};
Don't you want to initialize it to `none`?

2021-03-31 12:43 UTC, vladzcloudius commented on tracing/tracing.hh
>      sstring request;
Drop `request`, please.

2021-03-31 12:45 UTC, vladzcloudius requested changes

2021-03-31 12:45 UTC, vladzcloudius commented on tracing/trace_state.hh
>       */
I think we should just kill it.
If somebody wants to be verbose - he/she should do it using tracing::trace(...) which allows a full blown formatting.

2021-03-31 12:48 UTC, vladzcloudius requested changes

2021-03-31 12:48 UTC, vladzcloudius commented on test/boost/tracing.cc
> -        // supervisor::notify("creating tracing");
How is this related to this patch?
Don't mix unrelated cleanups with the functional patch.
Send this as a separate patch if needed.

2021-03-31 12:48 UTC, vladzcloudius commented on test/boost/tracing.cc
> -        // supervisor::notify("starting tracing");
same here

2021-03-31 12:52 UTC, vladzcloudius requested changes
I don't understand why this patch is needed and why do you need anything except for catching the shared_ptr as described in that comment.

2021-03-31 12:52 UTC, vladzcloudius commented on tracing/trace_state.cc
> +    // TODO: move to the shared_ptr to ensure we keep queries
This comment is confusing. 
Please, remove it.

2021-03-31 14:03 UTC, vladzcloudius requested changes

2021-03-31 14:03 UTC, vladzcloudius commented on tracing/trace_state.cc
> +        build_parameters_map_for_one_prepared(prepared_statements[i], vals.query_option_names[i], vals.query_option_values[i], param_key("param", i, psize <= 1));
I'm not sure I understand why you needed to change the loop so much while all what's changed is the place you get the query string from.

2021-03-31 14:18 UTC, vladzcloudius reviewed
Why only 2 allocations? I see at least 5.

2021-03-31 14:42 UTC, vladzcloudius requested changes

2021-03-31 14:42 UTC, vladzcloudius commented on tracing/trace_state.hh
> -    gms::inet_address _client;
Why did you need to move this and others up and down?
Please, separate functional changes from the cleanups. 
It makes it very hard to understand what is really going on here.

2021-03-31 14:42 UTC, vladzcloudius commented on tracing/trace_state.hh
> +    trace_type _command = trace_type::NONE;
Please, arrange these in a nice struct so that it would be very clear that these are going to eb copied into the one_session_records.

2021-03-31 14:42 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +                        if (records->session_rec.elapsed < _local_tracing.slow_query_threshold()) {
This changes the semantics of the slow_query_threshold.
Please, send changes related to this as a separate patch outside this series.
I doubt this change delivers any measurable performance gain.

2021-03-31 14:42 UTC, vladzcloudius commented on tracing/trace_state.cc
> +    utils::small_vector<sstring, 1> tables;
Why these lines are needed?

2021-03-31 14:42 UTC, vladzcloudius commented on tracing/trace_state.hh
>      lw_shared_ptr<one_session_records> _records;
Why, instead of this whole patch not to store `one_session_record` as a field in the trace_state and create a copy of it only when needed - when you pass it to a different layer (e.g. to the I/O backend).

This way you'll achieve exactly same (actually probably better) result without needed to do that many changes.

2021-03-31 14:46 UTC, vladzcloudius requested changes

2021-03-31 14:46 UTC, vladzcloudius commented on tracing/trace_state.hh
> +            return default_session_id;
This can only work for a Slow Logging Fast tracing mode where you never ask for a tracing on the remote node.
In all other modes you need to pass the real UUID to the remote side.

2021-03-31 14:48 UTC, vladzcloudius requested changes
Again, you are trying to optimize a non-Tracing path.
Why do you care?

2021-03-31 14:48 UTC, vladzcloudius commented on tracing/trace_state.hh
> -    friend void stop_foreground_prepared(const trace_state_ptr& state, const cql3::query_options* prepared_options_ptr) noexcept;
Where did this go?

2021-03-31 14:53 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    inline bool is_set(trace_string_enum val) {
I think boolean operator is a better choice.

2021-03-31 14:54 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    inline const char *to_string(trace_string_enum val) {
The advantage is a more laconic (hence more readable) call site.

2021-03-31 15:08 UTC, sitano commented on tracing/trace_state.hh
> -    friend void stop_foreground_prepared(const trace_state_ptr& state, const cql3::query_options* prepared_options_ptr) noexcept;
I don't know

2021-03-31 15:11 UTC, sitano commented on tracing/trace_state.hh
> +            return default_session_id;
no, there is 1 use case that is too general - the tracing error assertion in the state_trace destructor - maybe we could delete it?

> https://github.com/sitano/scylla/pull/2/commits/62b1475f5c75f5f706ffa25a1a19b2bfad718202#diff-bddf710626ec338c0b779c234871530ed27a052367dc4018f44b55ea2e534c22R270-R273

2021-03-31 15:16 UTC, sitano commented on tracing/trace_state.hh
>      lw_shared_ptr<one_session_records> _records;
because `one_session_record` has different lifetime characteristics and also is part of the tracing record, not part of the tracing context. context exists temporary, `one_session_record` exists beyond that is may outlive at least during postponed writes. See https://github.com/sitano/scylla/pull/2/commits/62b1475f5c75f5f706ffa25a1a19b2bfad718202#diff-bddf710626ec338c0b779c234871530ed27a052367dc4018f44b55ea2e534c22R359.

2021-03-31 15:16 UTC, sitano commented on tracing/trace_state.cc
> +    utils::small_vector<sstring, 1> tables;
because we postpone creation of the one_session_record.

2021-03-31 15:21 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +                        if (records->session_rec.elapsed < _local_tracing.slow_query_threshold()) {
> This changes the semantics of the slow_query_threshold.

how?

> Please, send changes related to this as a separate patch outside this series.

Then the patch will not work because I have deleted this parameter from the records.

2021-03-31 15:21 UTC, sitano commented on tracing/trace_state.hh
> +    trace_type _command = trace_type::NONE;
Why it's not clear? 

I can flatten params then I move everything there.

2021-03-31 15:22 UTC, sitano commented on tracing/trace_state.hh
> -    gms::inet_address _client;
because those fields logically are touched by different pieces of code compared to the 

```
    trace_state_props_set _state_props;
    state _state = state::inactive;
    ```

2021-03-31 15:23 UTC, sitano commented on tracing/trace_state.cc
> +        build_parameters_map_for_one_prepared(prepared_statements[i], vals.query_option_names[i], vals.query_option_values[i], param_key("param", i, psize <= 1));
because there were special case when there is only 1 val and when there are X vals, and I needed X+1 val.

2021-03-31 16:01 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +                        if (records->session_rec.elapsed < _local_tracing.slow_query_threshold()) {
this is probably a bug by me because elapsed will not be set for non primary records that still have to be saved. also as Vlad correctly mentioned on other nodes thresholds may be not configured.

2021-03-31 16:16 UTC, sitano commented on tracing/trace_state.cc
> +        build_parameters_map_for_one_prepared(prepared_statements[i], vals.query_option_names[i], vals.query_option_values[i], param_key("param", i, psize <= 1));
rework  to disconnect semantical parts

2021-04-01 13:22 UTC, sitano commented on transport/server.cc
> +    if (init_trace && trace_state) {
removed

2021-04-01 13:23 UTC, sitano commented on tracing/trace_string.cc
> +const char *trace_string_data[] = {
now with operators

2021-04-01 13:23 UTC, sitano commented on tracing/trace_string.hh
> +    inline bool is_set(trace_string_enum val) {
now with operators

2021-04-01 13:23 UTC, sitano commented on tracing/trace_string.hh
> +    inline const char *to_string(trace_string_enum val) {
now with operator*

2021-04-01 13:23 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +    std::string_view request = record.request;
removed with begin(string)

2021-04-01 13:23 UTC, sitano commented on tracing/tracing.hh
> +    trace_string_enum request_type = {};
moved to default type constructor

2021-04-01 13:24 UTC, sitano commented on tracing/tracing.hh
>      sstring request;
dropped, removed with begin(string)

2021-04-01 13:24 UTC, sitano commented on tracing/trace_state.hh
>       */
killed

2021-04-01 13:24 UTC, sitano commented on test/boost/tracing.cc
> -        // supervisor::notify("creating tracing");
extracted

2021-04-01 13:24 UTC, sitano commented on test/boost/tracing.cc
> -        // supervisor::notify("starting tracing");
extracted

2021-04-01 13:24 UTC, sitano commented on tracing/trace_state.cc
> +    // TODO: move to the shared_ptr to ensure we keep queries
removed

2021-04-01 13:24 UTC, sitano commented on tracing/trace_state.cc
> +        build_parameters_map_for_one_prepared(prepared_statements[i], vals.query_option_names[i], vals.query_option_values[i], param_key("param", i, psize <= 1));
reworked

2021-04-01 13:25 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +                        if (records->session_rec.elapsed < _local_tracing.slow_query_threshold()) {
thanks its not a bug because this part of the code writes only the final session to the node_slow table. however, I am returning it back as it is does not relate to this patch.

2021-04-01 13:35 UTC, sitano commented on tracing/trace_state.hh
> -    friend void stop_foreground_prepared(const trace_state_ptr& state, const cql3::query_options* prepared_options_ptr) noexcept;
extracted no a diff patch

2021-04-01 13:37 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +                        if (records->session_rec.elapsed < _local_tracing.slow_query_threshold()) {
previosly, records->do_log_slow_query depended only on local non serialized tracing.slow_query_threshold() so that code does not change semantics

2021-04-01 15:43 UTC, sitano commented on tracing/trace_state.hh
> -    gms::inet_address _client;
moved to flat _records

2021-04-01 15:43 UTC, sitano commented on tracing/trace_state.hh
> +    trace_type _command = trace_type::NONE;
moved to flat _records

2021-04-01 15:43 UTC, sitano commented on tracing/trace_state.cc
> +    utils::small_vector<sstring, 1> tables;
moved to flat _records

2021-04-01 15:43 UTC, sitano commented on tracing/trace_state.hh
>      lw_shared_ptr<one_session_records> _records;
moved to flat _records

2021-04-01 15:44 UTC, sitano commented on tracing/trace_state.hh
> +            return default_session_id;
moved to flat _records

2021-04-02 10:49 UTC, sitano commented
@vladzcloudius next round please

2021-04-02 19:20 UTC, vladzcloudius requested changes

2021-04-02 19:20 UTC, vladzcloudius commented on tracing/trace_string.hh
> +inline const seastar::sstring &operator*(trace_string_enum val) {
Some cosmetics:
* "&" should be attached to the type (Avi's code style) like this: `const sstring&`
* No need to use the `seastar::sstring` - include `seastarx.hh` and it is going to introduce a `seastar` namespace into your scope.

2021-04-02 19:20 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    return trace_string_data[static_cast<int>(val)];
No range check. Better use `at()`

2021-04-02 19:20 UTC, vladzcloudius commented on tracing/trace_string.hh
> +inline bool operator!(trace_string_enum val) {
Better implement `operator bool`.
See more on "why" here: https://en.cppreference.com/w/cpp/language/operators

2021-04-02 19:49 UTC, vladzcloudius requested changes

2021-04-02 19:49 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +    if (request.empty() && !!record.request_type) {
Here you go.
If you had an `operator::bool` you wouldn't need this `!!` nonsense.

2021-04-02 19:49 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +    std::string_view request = record.request;
I would squash the patches that introduce the `begin(type)` and remove all other `begin(...)` into a single patch.

2021-04-02 19:49 UTC, vladzcloudius commented on tracing/trace_state.cc
> +            params_map.emplace(param_key("query", i, psize <= 1), prepared_ptr ? prepared_ptr->statement->raw_cql_statement : "[lost]");
Not good.
We want to always have a query string.
Please, always catch the `prepared->statement` when a `tracing::add_prepared_statement(...)` is called.

2021-04-02 19:49 UTC, vladzcloudius commented on tracing/trace_state.cc
> +sstring param_key(const char *key, size_t index, bool single) {
How this is related to what this patch claims to do?

This patch is supposed to catch the `prepared->statement` shared_ptr and then use `statement->cql_raw_query` instead of `request.query`. 

Please, introduce a `param_key` beautifier as a separate patch.

2021-04-02 19:49 UTC, vladzcloudius commented on tracing/trace_state.cc
> +    std::vector<shared_ptr<cql3::cql_statement>> cql_statements;
It's very bad that you create a state of the tree when there is a point where Tracing is broken (after the previous patch).

Please, re-arrange this and the previous patches as follows:
1) One that introduces `params_key`: definition and usage.
2) One that changes copying the prepared statement query string to catching the shared_ptr.

2021-04-02 19:56 UTC, vladzcloudius requested changes

2021-04-02 19:56 UTC, vladzcloudius commented on tracing/trace_state.cc
> +    _params_ptr->cql_statements.emplace_back(prepared->statement);
What if the second `emplace` throws?

2021-04-02 19:57 UTC, vladzcloudius requested changes

2021-04-02 19:57 UTC, vladzcloudius commented on tracing/trace_state.cc
> +    // provides an access to the cql3 statements of present prepared statements
Better have a single vector of structs than multiple vectors when both vectors are always appended together.

2021-04-02 20:08 UTC, vladzcloudius requested changes

2021-04-02 20:08 UTC, vladzcloudius commented on transport/server.cc
> -    tracing::set_request_size(trace_state, fbuf.bytes_left());
Again, this is not going to optimize a Tracing hot path but rather a not-Tracing hot path.

Please, exclude these from this series and send them as a follow up.

2021-04-02 20:08 UTC, vladzcloudius commented on transport/server.cc
> +            if (trace_state && (trace_state->full_tracing() || trace_state->should_log_slow_query(trace_state->elapsed()))) {
This is bogus: what if `trace_state->should_log_slow_query(trace_state->elapsed()))` returns you `false` here but it would return true during the following call of `tracing::stop_foreground(trace_state)`?

It will result in `trace_state` missing data.

2021-04-02 21:39 UTC, vladzcloudius requested changes

2021-04-02 21:39 UTC, vladzcloudius commented on tracing/trace_state.hh
> +            copy->my_span_id = _records.my_span_id;
Implement a copy-constructor for a `one_session_records`, please.
But even that is not going to be good enough because one_session_records contains not only a static data but also contains a state (e.g. `_is_pending_for_write`) and is also used to access and modify the Tracing state via `budget_ptr` and the later is a rather non-trivial since I dynamically change the `budget_ptr` depending in which state the current one_session_records object is right now. Namely the specific `budget_ptr` represents a part of the `one_session_records` object state.

I have another idea: I think the main reason for a performance penalty here is a dereference operation, so instead of flattening `one_session_records` you can try to cache references to corresponding fields:

```
trace_state {
....
std::vector<sstring>& _queries;
```
and then 
```
trace_state::trace_state(...) 
: _queries(_params_ptr->queries)
...
```

and then you'll have 
```
void trace_state::add_query(sstring_view val) {
    _queries.emplace_back(std::move(val));
}
```

I suspect this would deliver you the majority of the benefit.

2021-04-05 08:42 UTC, sitano commented on transport/server.cc
> +            if (trace_state && (trace_state->full_tracing() || trace_state->should_log_slow_query(trace_state->elapsed()))) {
I don't see @vladzcloudius how is that bogus.

1. This patch gave me about 1-1.5% of win in our test by saving dynamic formatting and allocating/coping username. I would not recheck that tho.
2. This `if` check is the latest coroutine in the sequence of request processing. At that point deferred stop_foreground call will be the next instruction right to it. So there will be NO data loss until an exception and it is possible to neglect the possibility of the data lose because its limit is 0.
3.  I thought of calculating _do_log_slow_query at this point and passing it to the stop_foreground call but that's too many changes for too little win. I rather rollback this patch than invest my time into it.

However, as I understand you dislike this optimization, so I will dequeue this patch without further ado.

2021-04-05 09:07 UTC, sitano commented on tracing/trace_state.hh
> +            copy->my_span_id = _records.my_span_id;
> Implement a copy-constructor for a one_session_records, please.

I can just merge my 2 patches so I will not have to keep this intermediate code and implement copy con.

> But even that is not going to be good enough because one_session_records contains not only a static data but also contains a state (e.g. _is_pending_for_write) and is also used to access and modify the Tracing state via budget_ptr and the later is a rather non-trivial since I dynamically change the budget_ptr depending in which state the current one_session_records object is right now. Namely the specific budget_ptr represents a part of the one_session_records object state.

Yes, you are correct. It's unfortunate it tracks both parameters and the state so I can't just copy it and forget it. I have to ensure that the budget will be properly tracked and I do that. The main issue with the budget tracking is that its returning is done outside of the main budget withdrawing code paths. And moreover, that the amount that is withdrawn depends on the Ready() state of the object. I thought to fix that, but now I think its too much toil for me to do it. 

> I have another idea: I think the main reason for a performance penalty here is a dereference operation, so instead of flattening one_session_records you can try to cache references to corresponding fields.

I don't know. The dereference is absent when I flattened `unique_ptr<one_session_records>` but the perf lowered. This is counter-intuitive. We expect it to be the opposite. 

What you shown in the code however:

```
trace_state {
....
std::vector<sstring>& _queries;
```

 is not used in our prep statement code path (_queries). What did you mean?

2021-04-05 09:08 UTC, sitano commented on transport/server.cc
> -    tracing::set_request_size(trace_state, fbuf.bytes_left());
It's too hard Vlad to make all those changes in separate patches. I will just dequeue it. On the other hand. It is a separate commit, right?

2021-04-05 09:10 UTC, sitano commented on tracing/trace_state.cc
> +    _params_ptr->cql_statements.emplace_back(prepared->statement);
Nothing bad will happen besides the loss of the statement. There are so many things that can throw in the middle and we will not get data. For would you suggest? Replacing it with a struct? Wrapping it try/catch? I don't see what will improve this.

2021-04-05 09:11 UTC, sitano commented on tracing/trace_state.cc
> +    std::vector<shared_ptr<cql3::cql_statement>> cql_statements;
ok, I will just merge htem.

2021-04-05 09:11 UTC, sitano commented on tracing/trace_state.cc
> +sstring param_key(const char *key, size_t index, bool single) {
ok, I will dequeue this completelly. It is too hard to keep such change separate Vlad.

2021-04-05 09:12 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +    std::string_view request = record.request;
Ok

2021-04-05 09:13 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +    if (request.empty() && !!record.request_type) {
There is no trivial way to implement this operator Vlad for `enum class`. I mean there is no way at all for enum classes. There are only workarounds that are not beautiful. That only add to code complexity. But ok. I will replace my simple ! operator with class+enum+bool.

2021-04-05 09:13 UTC, sitano commented on tracing/trace_string.hh
> +inline bool operator!(trace_string_enum val) {
There is no trivial way to implement this operator Vlad for enum class. I mean there is no way at all for enum classes. There are only workarounds that are not beautiful. That only add to code complexity. But ok. I will replace my simple ! operator with class+enum+bool.

2021-04-05 09:13 UTC, sitano commented on tracing/trace_string.hh
> +    return trace_string_data[static_cast<int>(val)];
Ok

2021-04-05 12:54 UTC, sitano commented on tracing/trace_state.cc
> +            params_map.emplace(param_key("query", i, psize <= 1), prepared_ptr ? prepared_ptr->statement->raw_cql_statement : "[lost]");
I have no idea how do you want me this to be done. 

I did not like it when it was:

```
- keys_size = query.size() + statements.size(), keys_index = 0
- add all queries(keys_size, keys_index)
- add all statements(keys_size, keys_index)
```

You don't like:

```
- if queries: add all queries()
- else: add all statements()
```

I don't see other options. Please, write the preudocode of what you want here. 

I am deleting my helper to let this code be left as bloated as it is.

2021-04-05 13:07 UTC, sitano commented on tracing/trace_string.hh
> +inline const seastar::sstring &operator*(trace_string_enum val) {
done

2021-04-05 13:08 UTC, sitano commented on tracing/trace_string.hh
> +inline bool operator!(trace_string_enum val) {
introduced 
```
class trace_string_enum
{
public:
    enum value_type : uint8_t
    {
        none = 0,
        prepare_stmt,
        execute_stmt,
        execute_prepared,
        execute_batch,
        alternator
    };

    trace_string_enum() = default;
    constexpr trace_string_enum(value_type type) : value(type) { }

    operator value_type() const { return value; }

    explicit operator const sstring&() const {
        return trace_string_data.at(value);
    }

    [[nodiscard]]
    bool empty() const { return !value; }

private:
    value_type value;
}
```

that is of course much more clean than a single enum class with 1 func.

2021-04-05 13:08 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +    if (request.empty() && !!record.request_type) {
done by operator

2021-04-05 13:08 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +    std::string_view request = record.request;
squashed

2021-04-05 13:08 UTC, sitano commented on tracing/trace_state.cc
> +sstring param_key(const char *key, size_t index, bool single) {
removed

2021-04-05 13:09 UTC, sitano commented on tracing/trace_state.cc
> +    std::vector<shared_ptr<cql3::cql_statement>> cql_statements;
merged

2021-04-05 13:10 UTC, sitano commented on transport/server.cc
> -    tracing::set_request_size(trace_state, fbuf.bytes_left());
dropped

2021-04-05 13:10 UTC, sitano commented on transport/server.cc
> +            if (trace_state && (trace_state->full_tracing() || trace_state->should_log_slow_query(trace_state->elapsed()))) {
dropped

2021-04-05 13:20 UTC, sitano commented on tracing/trace_state.cc
> +    _params_ptr->cql_statements.emplace_back(prepared->statement);
replaced with struct that however does not change anything if emplace will throw

2021-04-05 13:21 UTC, sitano commented on tracing/trace_state.cc
> +    // provides an access to the cql3 statements of present prepared statements
intro-ed statement_param

2021-04-05 13:35 UTC, sitano commented
@vladzcloudius next round

2021-04-06 12:07 UTC, sitano commented on tracing/trace_string.hh
> +    return trace_string_data[static_cast<int>(val)];
sadly saying it's impossible to write a static_assert against 

- enum size
- vector size - non const

2021-04-06 12:10 UTC, sitano commented on tracing/trace_string.hh
> +inline bool operator!(trace_string_enum val) {
My best effort to keep enum and strings as close as possible:
```
namespace tracing {

namespace string {

    enum value_type : uint8_t
    {
        none = 0,
        prepare_stmt,
        execute_stmt,
        execute_prepared,
        execute_batch,
        alternator
    };

    // the number of elements must match value_type enum
    inline std::vector<sstring> trace_string_data = {
        "None",
        "Preparing CQL3 query",
        "Execute CQL3 query",
        "Execute CQL3 prepared query",
        "Execute batch of CQL3 queries",
        "Alternator"
    };

}

class trace_string_enum
{
public:
    using value_type = tracing::string::value_type;

    trace_string_enum() = default;
    constexpr trace_string_enum(value_type type) : value(type) { }

    explicit operator bool() const { return empty(); }

    sstring operator*() const {
        return string::trace_string_data.at(value);
    }

    [[nodiscard]]
    bool empty() const { return !value; }

private:
    value_type value;
};
```

> trace_string_enum() = default;

default empty constructor is required to be able to write

```
trace_string_enum();
trace_string_enum a = {};
trace_string_enum b = trace_string_enum();
or anything alike
```

2021-04-06 12:21 UTC, sitano commented on tracing/trace_state.cc
> +            params_map.emplace(param_key("query", i, psize <= 1), prepared_ptr ? prepared_ptr->statement->raw_cql_statement : "[lost]");
extracting into separate patch

2021-04-06 12:45 UTC, sitano commented on tracing/trace_state.cc
> +sstring param_key(const char *key, size_t index, bool single) {
recovered into separate patch

2021-04-06 12:45 UTC, sitano commented on tracing/trace_state.cc
> +    _params_ptr->cql_statements.emplace_back(prepared->statement);
replaced with a single struct

2021-04-06 12:49 UTC, sitano commented on tracing/trace_state.cc
> +            params_map.emplace(param_key("query", i, psize <= 1), prepared_ptr ? prepared_ptr->statement->raw_cql_statement : "[lost]");
replaced with 
```
    auto& statements = vals.prepared_statements;
    const size_t psize = statements.size();
    if (psize) {
        // Parameter's key in the map will be "param[X]" for a single query CQL command and "param[Y][X] for a multiple
        // queries CQL command, where X is an index of the parameter in a corresponding query and Y is an index of the
        // corresponding query in the BATCH.
        for (size_t i = 0; i < psize; ++i) {
            build_parameters_map_for_one_prepared(statements[i].prepared, vals.query_option_names[i], vals.query_option_values[i], param_key("param", i, psize));
            params_map.emplace(param_key("query", qsize+i, qsize+psize), statements[i].cql->raw_cql_statement);
        }
    }
    ```

2021-04-06 13:01 UTC, sitano commented on tracing/trace_state.hh
> +            copy->my_span_id = _records.my_span_id;
testing simplified version perf

2021-04-06 13:46 UTC, sitano commented
alternative https://github.com/sitano/scylla/tree/tracing_optimize_hot_path6 without removing unique_ptr allocation of one_record on hot path

2021-04-07 16:14 UTC, sitano commented
new alternative https://github.com/sitano/scylla/tree/tracing_optimize_hot_path7
- no patch to omit one_session_record allocation and session_id and span_id generation
- username to lw_shared_ptr in client_state

2021-04-08 13:00 UTC, vladzcloudius requested changes

2021-04-08 13:00 UTC, vladzcloudius commented on tracing/trace_string.hh
> +namespace string {
tracing::string::XX - this is cool!

2021-04-08 13:00 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    explicit operator bool() const { return empty(); }
Do you really want `bool` to be explicit?

2021-04-08 13:00 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    enum value_type : uint8_t
`enum class`, no?

2021-04-08 13:00 UTC, vladzcloudius commented on tracing/trace_string.hh
> +    bool empty() const { return !value; }
here better use `value == value_type::none`. 
It's, first, more readable and more robust - what if `value_type::none` stops being 0 in the future?

Another way to ensure that this doesn't break is to add a static assert that would check that `none == 0`

2021-04-08 13:04 UTC, vladzcloudius requested changes
Please, add a note in the patch description that you are removing the prepared statement ID in the process.

2021-04-08 13:32 UTC, vladzcloudius requested changes
Same here. This patch introduces a new thing - put some more text about it.

2021-04-08 13:34 UTC, vladzcloudius approved these changes
Very nice!

2021-04-08 14:14 UTC, sitano commented on tracing/trace_string.hh
> +    explicit operator bool() const { return empty(); }
usual practice not to make bool conversion implicit because it may then implicitly convert to integer

2021-04-08 14:14 UTC, sitano commented on tracing/trace_string.hh
> +    enum value_type : uint8_t
if I will do that enum class, then it will be not `tracing::string::begin` but `tracing::string::value_type::begin`

2021-04-08 14:15 UTC, sitano commented on tracing/trace_string.hh
> +    bool empty() const { return !value; }
good point

2021-04-08 14:25 UTC, vladzcloudius requested changes

2021-04-08 14:25 UTC, vladzcloudius commented on tracing/trace_state.cc
> +static sstring param_key(const char *key, size_t index, size_t size) {
Why not to make it a private method of a `trace_state`?

Also, add an JavaDoc description for this new function/method, please.

2021-04-08 14:25 UTC, vladzcloudius commented on tracing/trace_state.cc
> +            params_map.emplace(param_key("query", qsize+i, qsize+psize), statements[i].cql->raw_cql_statement);
Nitpicks: unlike in Python Avi's codding style requires spaces around `+`: like this:
```
params_map.emplace(param_key("query", qsize + i, qsize + psize), statements[i].cql->raw_cql_statement);
```

And the description of the patch is not the best - this patch is more about saving a string copy in the tracing hot path than just saving a function call. The reader wouldn't understand that one leads to another - you should to be explicit.

Except for that - very nice!

2021-04-08 14:25 UTC, vladzcloudius commented on transport/server.cc
> +            tracing::set_request_size(trace_state, fbuf.bytes_left());
How is this patch related to this series?
It optimized a non-tracing path.

Please, send it as a follow up patch.

2021-04-08 14:25 UTC, vladzcloudius commented on cql3/query_processor.hh
> +    statements::prepared_statement::checked_weak_ptr get_prepared(const lw_shared_ptr<auth::authenticated_user>& user, const prepared_cache_key_type& key) {
About the patch description: here, again, it's not about formatting it's about string copy in a hot path that you postpone now.

So, the current description of the patch doesn't help understanding the right motivation.

2021-04-08 14:25 UTC, vladzcloudius commented on test/boost/cql_auth_query_test.cc
> +    const auto reset = defer([&cs, old_user] {
This is not going to work as expected.
Original lines are restoring the user name as it was before the `f()` call which probably modifies the value of `cs.user()`. 

So, by catching the shared pointer to it you are not going to achieve the original goal.
You need to catch the *value* of the original user, namely `[..., old_user = *cs.user()]`

2021-04-08 14:25 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +    std::strstream username; username << *record.user ;
I don't mind but you may get a comment about not breaking a line after `;`.

2021-04-08 14:25 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +        cql3::raw_value::make_value(utf8_type->decompose(sstring(username.str()))),
do you really need an explicit cast to `sstring` here?

2021-04-08 14:25 UTC, vladzcloudius commented on tracing/tracing.hh
> +inline lw_shared_ptr<auth::authenticated_user> _default_unauthenticated_user = make_lw_shared(auth::authenticated_user());
This is not going to work.
lw_shared_ptr can only live on the same shard it's been allocated on.
So, in order to achieve what you want to achieve here you need to create a non-static private field in one of the per-shard tracing objects, like `tracing::tracing` and then use it  in a default constructor.

2021-04-08 14:56 UTC, sitano commented on tracing/trace_string.hh
> +    bool empty() const { return !value; }
done

2021-04-08 14:56 UTC, sitano commented on tracing/trace_state.cc
> +            params_map.emplace(param_key("query", qsize+i, qsize+psize), statements[i].cql->raw_cql_statement);
done

2021-04-08 15:01 UTC, sitano commented on test/boost/cql_auth_query_test.cc
> +    const auto reset = defer([&cs, old_user] {
I agree that in that specific case its better to catch by val but it works here because when the test calls `cs.set_login(auth::authenticated_user(sstring(user_name)));` it changes the place where the `client_state._user` points to. So that `old_user` pointer is untouched.

2021-04-08 16:25 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +        cql3::raw_value::make_value(utf8_type->decompose(sstring(username.str()))),
no, I misinterpreted decompose semantics

2021-04-08 16:26 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +        cql3::raw_value::make_value(utf8_type->decompose(sstring(username.str()))),
removed

2021-04-08 16:27 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +    std::strstream username; username << *record.user ;
breaked

2021-04-08 16:27 UTC, sitano commented on transport/server.cc
> +            tracing::set_request_size(trace_state, fbuf.bytes_left());
it is a separate patch

2021-04-08 16:28 UTC, sitano commented on tracing/trace_state.cc
> +static sstring param_key(const char *key, size_t index, size_t size) {
static makes it already private enough to the translation unit. no need in making it part of the trace_state declaration. no need in declaring it in the header.

2021-04-08 16:29 UTC, sitano commented on tracing/tracing.hh
> +inline lw_shared_ptr<auth::authenticated_user> _default_unauthenticated_user = make_lw_shared(auth::authenticated_user());
lol, this is my bad

2021-04-08 16:38 UTC, sitano commented on tracing/tracing.hh
> +inline lw_shared_ptr<auth::authenticated_user> _default_unauthenticated_user = make_lw_shared(auth::authenticated_user());
removed completely

2021-04-08 16:38 UTC, sitano commented on cql3/query_processor.hh
> +    statements::prepared_statement::checked_weak_ptr get_prepared(const lw_shared_ptr<auth::authenticated_user>& user, const prepared_cache_key_type& key) {
I think now it's better

2021-04-08 16:40 UTC, sitano commented
@vladzcloudius all comments addressed. next round pls.

2021-04-08 16:42 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +        cql3::raw_value::make_value(utf8_type->decompose(sstring(username.str()))),
replaced with helper
```
+static sstring user_to_string(const lw_shared_ptr<auth::authenticated_user>& user) {
+    std::strstream username;
+    if (user) {
+        username << *user;
+    } else {
+        username << auth::anonymous_user();
+    }
+    return sstring(username.str());
+}
```

2021-04-08 18:28 UTC, vladzcloudius requested changes

2021-04-08 18:28 UTC, vladzcloudius commented on alternator/server.cc
>          std::string buf;
Paragraph 2 and 3 in the description are telling the same (very similar) thing but in different words. I think you should drop one of them.

2021-04-08 18:28 UTC, vladzcloudius commented on tracing/trace_state.cc
> +static sstring param_key(const char *key, size_t index, size_t size) {
Oh, I see... Makes sense.

2021-04-08 18:28 UTC, vladzcloudius commented on tracing/trace_state.cc
>  logging::logger trace_state_logger("trace_state");
Change the subject of the patch, please. - It doesn't express what this patch really is about.
I think something like "tracing: avoid copying a query string in a prepared statements tracing hot path" would be clearer.

2021-04-08 18:28 UTC, vladzcloudius commented on transport/server.cc
> +            tracing::set_request_size(trace_state, fbuf.bytes_left());
I mean a separate patch NOT in this PR.
Send it as a follow up (after this PR).

2021-04-08 18:28 UTC, vladzcloudius commented on test/boost/cql_auth_query_test.cc
> +    const auto reset = defer([&cs, old_user] {
This is the internal implementation detail. In the future someone may decide to change it so that when `set_login()` is called the value is assigned and not the whole shared_pointer is re-allocated and the test will break.

2021-04-08 18:28 UTC, vladzcloudius commented on tracing/trace_state.hh
> +    void set_user(const lw_shared_ptr<auth::authenticated_user>& user) {
better change to passing the parameter by value and use std::move during the assignment.
This is a more modern C++ way.

2021-04-08 18:28 UTC, vladzcloudius commented on tracing/trace_keyspace_helper.cc
> +static sstring user_to_string(const lw_shared_ptr<auth::authenticated_user>& user) {
I wonder why you need all this?
The original code has an assignment from auth::authenticated_user to sstring. 

And most importantly you are breaking the abstraction: trace_keyspace_helper should have no idea about the trace_state related logic.

here the change should be as simple as:

```
-        cql3::raw_value::make_value(utf8_type->decompose(record.username)),
+        cql3::raw_value::make_value(utf8_type->decompose(sstring(*record.user))),
```

But even this is not good enough because "unathenticated request is not the same as a request that is authenticated with an `anonymous_user`.

So, you may want to implement a `trace_state::get_username_string()` method that would preserve the current functionality and have the logic similar to below inside.

2021-04-08 18:28 UTC, vladzcloudius commented on tracing/trace_state.hh
> +inline void set_user(const trace_state_ptr& p, const lw_shared_ptr<auth::authenticated_user>& user) {
Same here - pass shared_pointers by value, please, and use std::move()

2021-04-08 18:28 UTC, vladzcloudius commented on transport/server.cc
>          cd.username = user_ptr->name;
Hold on! Here is your username string! It's freaking `public`!

2021-04-08 20:29 UTC, vladzcloudius requested changes

2021-04-08 20:29 UTC, vladzcloudius commented on test/boost/cql_auth_query_test.cc
> +    auto old_user = *(cs.user());
ditch brackets

2021-04-08 20:29 UTC, vladzcloudius commented on tracing/trace_string.hh
> +
remove null-string

2021-04-09 08:18 UTC, sitano commented on tracing/trace_string.hh
> +    explicit operator bool() const { return empty(); }
removed

2021-04-09 08:18 UTC, sitano commented on tracing/trace_string.hh
> +    enum value_type : uint8_t
my best enum I have every created
```
+enum class string_type : uint8_t
+{
+    none = 0,
+    prepare_stmt,
+    execute_stmt,
+    execute_prepared,
+    execute_batch,
+    alternator,
+    last
+};
+
+inline std::array<const char *, 1+static_cast<size_t>(string_type::last)> trace_string_data = {
+    "None",
+    "Preparing CQL3 query",
+    "Execute CQL3 query",
+    "Execute CQL3 prepared query",
+    "Execute batch of CQL3 queries",
+    "Alternator",
+    "Last"
+};
+
+// none == 0 is the default value.
+static_assert(static_cast<size_t>(string_type::none) == 0);
+
+class trace_string_enum
+{
+public:
+    trace_string_enum() = default;
+    constexpr trace_string_enum(string_type type) : value(type) { }
+
+    sstring operator*() const {
+        return trace_string_data[static_cast<size_t>(value)];
+    }
+
+    [[nodiscard]]
+    bool empty() const { return value == string_type::none; }
+
+private:
+    string_type value;
+};
```

2021-04-09 08:32 UTC, sitano commented on transport/server.cc
> +            tracing::set_request_size(trace_state, fbuf.bytes_left());
extracted out

2021-04-09 08:34 UTC, sitano commented on test/boost/cql_auth_query_test.cc
> +    const auto reset = defer([&cs, old_user] {
yes, this is fixed

2021-04-09 08:35 UTC, sitano commented on alternator/server.cc
>          std::string buf;
fixed

2021-04-09 08:35 UTC, sitano commented on tracing/trace_state.cc
>  logging::logger trace_state_logger("trace_state");
changed

2021-04-09 08:52 UTC, sitano commented on tracing/trace_state.hh
> +    void set_user(const lw_shared_ptr<auth::authenticated_user>& user) {
changed to move

2021-04-09 08:53 UTC, sitano commented on tracing/trace_keyspace_helper.cc
> +static sstring user_to_string(const lw_shared_ptr<auth::authenticated_user>& user) {
can't  move it to trace_state. `user_to_string` moved to `session_record::get_username_string()`

2021-04-09 08:54 UTC, sitano commented on test/boost/cql_auth_query_test.cc
> +    auto old_user = *(cs.user());
yep

2021-04-09 08:54 UTC, sitano commented on tracing/trace_string.hh
> +
removed

2021-04-09 08:54 UTC, sitano commented on tracing/trace_state.hh
> +inline void set_user(const trace_state_ptr& p, const lw_shared_ptr<auth::authenticated_user>& user) {
passed

2021-04-09 08:54 UTC, sitano commented
@vladzcloudius all comments addressed. next round pls.

2021-04-12 12:39 UTC, closed without merging